language: julia

julia:
 - release

notifications:
 email: false

after_success:
 - julia -e 'cd(Pkg.dir("Carretera")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
